# Number of bootnode. Will not scale automatically unless keys etc.. are pre-provisionned.

image:
  tag: "develop"

besu:
  persistentVolume:
    enabled: false # TODO: add on START!
    # storageClass: gp2
    # size: 4Gi
    # annotations: {}

bootnode:
  enabled: true
  # privKey: "0xaa2b3f25329076ba5dd09fcd8d64218c5e1145694ad4feb5b7a461da86f1e3c5"

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

ingress_http:
  enabled: true
  # annotations:
  #   ingress.kubernetes.io/ssl-redirect: "true"
  #   kubernetes.io/tls-acme: "true"
  #   certmanager.k8s.io/cluster-issuer: letsencrypt-production
  # path: /
  # hosts:
  #   - k8s.localhost.lan
  # tls:
  #  - secretName: clique-tls
  #    hosts:
  #      - k8s.localhost.lan

ingress_ws:
  enabled: true
  # annotations:
  #   ingress.kubernetes.io/ssl-redirect: "true"
  #   kubernetes.io/tls-acme: "true"
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  #   certmanager.k8s.io/cluster-issuer: letsencrypt-production
  # path: /ws
  # hosts:
  #   - k8s.localhost.lan
  # tls:
  #  - secretName: clique-tls
  #    hosts:
  #      - k8s.localhost.lan
